#pragma once

#include <cstdint>
#include <vector>

namespace brightchain {

/**
 * HMAC-DRBG (NIST SP 800-90A) for deterministic random bit generation
 * Used for generating deterministic primes in Paillier key derivation
 */
class HMAC_DRBG {
public:
    explicit HMAC_DRBG(const std::vector<uint8_t>& seed);
    
    /**
     * Generate deterministic random bytes
     * @param num_bytes Number of bytes to generate
     * @return Generated bytes
     */
    std::vector<uint8_t> generate(size_t num_bytes);
    
private:
    std::vector<uint8_t> v_;
    std::vector<uint8_t> k_;
    
    void update(const std::vector<uint8_t>& data);
    void hmac(const std::vector<uint8_t>& key, const std::vector<uint8_t>& data, 
              std::vector<uint8_t>& out);
};

} // namespace brightchain
